version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env
    command: npm start

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
