version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  web_scraper_publisher:
    build: .
    command: node src/jobs/property_type_publisher.js
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
  web_scraper_consumer:
    build: .
    command: node main.js
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
