version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  web_scraper_publisher:
    build: .
    command: node src/jobs/worker_publisher.js
    volumes:
      - .:/home/pptruser/app
    depends_on:
      - rabbitmq
    restart: always
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
  web_scraper_consumer:
    build: .
    command: node src/jobs/worker_consumer.js
    volumes:
      - .:/home/pptruser/app
    depends_on:
      - rabbitmq
      - mysql
    restart: always
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_scraper
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always